export const tools=[
{id:'calc',category:'Produktivitas',name:'Kalkulator',desc:'Hitung matematika dengan cepat.',icon:'🧮',type:'text'},
{id:'percent',category:'Produktivitas',name:'Persentase',desc:'Hitung nilai persentase.',icon:'％',type:'text'},
{id:'date',category:'Produktivitas',name:'Tanggal',desc:'Lihat tanggal sekarang.',icon:'📅',type:'text'},
{id:'stopwatch',category:'Produktivitas',name:'Stopwatch',desc:'Pengukur waktu sederhana.',icon:'⏱️',type:'text'},
{id:'words',category:'Teks',name:'Word Counter',desc:'Hitung kata dan karakter.',icon:'🔤',type:'text'},
{id:'upper',category:'Teks',name:'Uppercase',desc:'Ubah teks menjadi huruf besar.',icon:'A',type:'uppercase'},
{id:'lower',category:'Teks',name:'Lowercase',desc:'Ubah teks menjadi huruf kecil.',icon:'a',type:'lowercase'},
{id:'reverse',category:'Teks',name:'Text Reverse',desc:'Balik susunan teks.',icon:'↔',type:'text'},
{id:'json',category:'Developer',name:'JSON Formatter',desc:'Rapikan JSON.',icon:'{}',type:'text'},
{id:'base64',category:'Developer',name:'Base64',desc:'Encode dan decode teks.',icon:'64',type:'text'},
{id:'uuid',category:'Developer',name:'UUID Generator',desc:'Buat UUID random.',icon:'#',type:'text'},
{id:'qr',category:'Developer',name:'QR Generator',desc:'Buat QR Code.',icon:'▦',type:'qr'},
{id:'scan',category:'Developer',name:'QR Scanner',desc:'Scan QR menggunakan kamera.',icon:'⌗',type:'scan'},
{id:'password',category:'Security',name:'Password Generator',desc:'Buat password random.',icon:'🔐',type:'text'},
{id:'color',category:'Utility',name:'Color Tool',desc:'Utility warna sederhana.',icon:'◉',type:'text'},
{id:'url',category:'Network',name:'URL Parser',desc:'Analisis struktur URL.',icon:'🔗',type:'text'},
{id:'ua',category:'Network',name:'User Agent',desc:'Lihat informasi browser.',icon:'🌐',type:'text'}];
